<?php
use FactorioItemBrowser\Api\Client\Entity\GenericEntityWithRecipes;

/* @var GenericEntityWithRecipes $entity */
$entity = $this->entity;
$numberOfOmittedRecipes = $entity->getTotalNumberOfRecipes() - count($entity->getRecipes());

if ($numberOfOmittedRecipes > 0) { ?>
    <a class="more-recipes" href="<?php // @todo echo $this->escapeHtmlAttr($helper->getDetailsUrl($headEntity)); ?>" data-link><?php
        echo $this->escapeHtml($this->replace($this->translatePlural('boxed-item more-recipes', '', $numberOfOmittedRecipes), ['count' => $numberOfOmittedRecipes]));
    ?></a>
<?php }
