<?php

use FactorioItemBrowser\Api\Client\Entity\Recipe;
use FactorioItemBrowser\Portal\View\Helper\GenericEntityHelper;
use FactorioItemBrowser\Portal\View\Helper\RecipeHelper;

/* @var GenericEntityHelper $genericEntityHelper */
$genericEntityHelper = $this->genericEntity();
/* @var RecipeHelper $recipeHelper */
$recipeHelper = $this->recipe();
/* @var Recipe $recipe */
$recipe = $this->recipe;
?>

<div class="recipe <?php echo $this->escapeHtmlAttr($recipeHelper->getRecipeMode($recipe)); ?>">
    <?php foreach ($recipe->getIngredients() as $ingredient) {
        echo $genericEntityHelper->renderLinkedIcon($ingredient, $ingredient->getAmount());
    } ?>
    <div class="separator">
        <?php if ($recipe->getCraftingTime() > 0) { ?>
            <span class="time"><?php
                echo $this->escapeHtml($this->format()->craftingTime($recipe->getCraftingTime()));
            ?></span>
        <?php } ?>
    </div>
    <?php foreach ($recipe->getProducts() as $product) {
        echo $genericEntityHelper->renderLinkedIcon($product, $product->getAmount());
    }

    if ($recipeHelper->highlightExpensiveRecipe($recipe)) { ?>
        <div class="mode"><?php echo $this->escapeHtml($this->translate('box-label expensive')); ?></div>
    <?php } ?>
</div>