<?php
use FactorioItemBrowser\Api\Client\Entity\Recipe;
use FactorioItemBrowser\Portal\View\Helper\RecipeHelper;

/* @var RecipeHelper $recipeHelper */
$recipeHelper = $this->recipe();
/* @var Recipe $recipe */
$recipe = $this->recipe;

$this->headTitle()->prepend($recipe->getLabel() ?: $recipe->getName());

echo $this->partial('portal::recipe/partial/recipe', ['recipe' => $recipeHelper->getPrimaryRecipe($recipe)]);
if ($recipeHelper->hasSecondaryRecipe($recipe)) {
    echo $this->partial('portal::recipe/partial/recipe', ['recipe' => $recipeHelper->getSecondaryRecipe($recipe)]);
}

if (count($this->machines) > 0) {
    echo $this->render('portal::recipe/partial/machines');
}