<?php
use FactorioItemBrowser\Api\Client\Entity\Recipe;
use FactorioItemBrowser\Api\Client\Entity\RecipeWithExpensiveVersion;

/* @var Recipe $recipe */
$recipe = $this->recipe;

$this->headTitle()->prepend($recipe->getLabel() ?: $recipe->getName());

echo $this->partial('portal::recipe/partial/recipe', ['recipe' => $recipe]);
if ($recipe instanceof RecipeWithExpensiveVersion && $recipe->hasExpensiveVersion()) {
    echo $this->partial('portal::recipe/partial/recipe', ['recipe' => $recipe->getExpensiveVersion()]);
}

if (count($this->machines) > 0) {
    echo $this->render('portal::recipe/partial/machines');
}