<?php
use FactorioItemBrowser\Api\Client\Entity\Machine;
use FactorioItemBrowser\Portal\Constant\Config;
use FactorioItemBrowser\Portal\Constant\RouteNames;

/* @var Machine[] $machines */
$machines = $this->machines;

foreach ($machines as $machine) {
    if ($machine->getName() === 'player') {
        echo $this->partial('portal::recipe/partial/machine/player', ['machine' => $machine]);
    } else {
        echo $this->partial('portal::recipe/partial/machine/machine', ['machine' => $machine]);
    }
}

if ($this->currentPage < $this->totalNumberOfMachines / Config::MACHINE_PER_PAGE) { ?>
    <li class="paginated-list-button"
        data-paginated-list="<?php echo $this->escapeHtmlAttr($this->url(RouteNames::RECIPE_MACHINE_PAGE, [
            'name' => $this->recipeName,
            'page' => $this->currentPage + 1
        ])); ?>"
    >
        <span class="default-wording"><?php echo $this->escapeHtml($this->translate('recipe-details machine load-more')); ?></span>
        <span class="loading-wording"><?php echo $this->escapeHtml($this->translate('recipe-details machine loading-more')); ?></span>
    </li>
<?php }