language: php

matrix:
  fast_finish: true
  include:
    - php: '7.2'
    - php: '7.3'

install:
  - composer install --prefer-dist --no-interaction --no-suggest

script:
  - composer validate --strict
  - vendor/bin/phpcs -np --colors
