version: "3.5"
services:

  php:
    build: ./docker/php
    container_name: fib-po-php
    image: fib-po-php
    volumes:
    - ".:/project"
    - "$SSH_AUTH_SOCK:/ssh-agent"
    networks:
    - network-fib
    ports:
    - 8020:80
    environment:
      FIB_ENV: development
      SSH_AUTH_SOCK: /ssh-agent

  mysql:
    container_name: fib-po-mysql
    image: bluepsyduck/mysql
    networks:
    - network-fib
    ports:
    - "13326:3306"

networks:
  network-fib:
    name: network-fib
