<?php
use FactorioItemBrowser\Api\Client\Entity\Icon;

/* @var array|Icon[] $icons */
$icons = $this->icons;

foreach ($icons as $icon) {
    $selectors = [];
    foreach ($icon->getEntities() as $entity) {
        $selectors[] = '.icon-' . $this->escapeCss(str_replace(' ', '_', $entity->getType() . '-' . $entity->getName()));
    }
    $fullSelector = implode(',', $selectors);

    echo $fullSelector . '{background-image:url(data:image/png;base64,' . base64_encode($icon->getContent()) . ');}' . PHP_EOL;
}
