<?php
use FactorioItemBrowser\Portal\View\Helper\SidebarHelper;

/* @var SidebarHelper $sidebarHelper */
$sidebarHelper = $this->sidebar();
?>

<input id="toggle-sidebar" type="checkbox" class="toggle-checkbox" />
<div id="sidebar">
    <label for="toggle-sidebar" class="sidebar-close"></label>

    <?php
        echo $this->render('layout::partial/sidebar/modLink');
        echo $this->render('layout::partial/sidebar/settingsLink');
    ?>

    <div class="sidebar-pinned-entity-list">
        <h3><?php echo $this->escapeHtml($this->translate('sidebar headline pinned')); ?></h3>
        <?php echo $sidebarHelper->renderPinnedEntities(); ?>
    </div>

    <div class="sidebar-unpinned-entity-list">
        <h3><?php echo $this->escapeHtml($this->translate('sidebar headline last-viewed')); ?></h3>
        <?php  echo $sidebarHelper->renderUnpinnedEntities(); ?>
    </div>
</div>
<label class="toggle-overlay" for="toggle-sidebar"></label>