<?php
use FactorioItemBrowser\Portal\Constant\RouteNames;

/* @var \FactorioItemBrowser\Portal\View\Helper\LayoutParamsHelper $layoutParamsHelper */
$layoutParamsHelper = $this->layoutParams();
?>

<div class="header-mod-teaser">
    <span><?php echo $this->escapeHtml($this->replace($this->translate('header mod-teaser label'), [
        'count' => $layoutParamsHelper->getNumberOfAvailableMods(),
        'number' => $layoutParamsHelper->getNumberOfEnabledMods()
    ])); ?></span>
    <a href="<?php echo $this->escapeHtmlAttr($this->url(RouteNames::MOD_LIST)); ?>" class="no-loading-circle" data-link><?php
        echo $this->escapeHtml($this->translate('header mod-teaser button'));
    ?></a>
</div>