<?php
use FactorioItemBrowser\Api\Client\Entity\Mod;

/* @var Mod $mod */
$mod = $this->mod;
/* @var bool $isEnabled */
$isEnabled = $this->isEnabled;

$modData = [
    'name' => $mod->getName(),
    'title' => $mod->getLabel(),
    'description' => $mod->getDescription(),
    'author' => $mod->getAuthor()
];
?>

<input
    id="mod_<?php echo $this->escapeHtmlAttr($mod->getName()); ?>"
    name="enabledMods[]"
    value="<?php echo $this->escapeHtmlAttr($mod->getName()); ?>"
    type="checkbox"
    <?php if ($mod->getIsEnabled()) { ?>checked<?php } ?>
    class="mod-checkbox hidden"
/>
<li class="mod"
    data-mod="<?php echo $this->escapeHtmlAttr(json_encode($modData)); ?>"
    data-label-for="mod_<?php echo $this->escapeHtmlAttr($mod->getName()); ?>"
>
    <label for="mod_<?php echo $this->escapeHtmlAttr($mod->getName()); ?>">
        <h3><?php echo $this->escapeHtml($mod->getLabel() ?: $mod->getName()); ?></h3>
        <?php echo $this->escapeHtml($mod->getDescription()); ?>
    </label>
    <div class="check-icon"></div>
    <dl>
        <dt><?php echo $this->escapeHtml($this->translate('mod name')); ?></dt>
        <dd><?php echo $this->escapeHtml($mod->getName()); ?></dd>

        <dt><?php echo $this->escapeHtml($this->translate('mod author')); ?></dt>
        <dd><?php echo $this->escapeHtml($mod->getAuthor()); ?></dd>

        <dt><?php echo $this->escapeHtml($this->translate('mod version')); ?></dt>
        <dd><?php echo $this->escapeHtml($mod->getVersion()); ?></dd>
    </dl>
</li>