<?php
use FactorioItemBrowser\Portal\Constant\RouteNames;
?>

<section>
    <h2><?php echo $this->escapeHtml($this->translate('mod-list upload-file')); ?></h2>

    <form class="mod-upload-form" method="post" action="<?php echo $this->escapeHtmlAttr($this->url(RouteNames::MOD_LIST_UPLOAD)); ?>" enctype="multipart/form-data">
        <input class="hidden" type="file" id="mod-upload-file" name="modListFile" />

        <label for="mod-upload-file" class="advanced-upload">
            <?php echo $this->translate('mod-list upload-file label advanced'); ?>
        </label>
        <label for="mod-upload-file" class="simple-upload">
            <?php echo $this->translate('mod-list upload-file label simple'); ?>
        </label>
        <label class="dragover">
            <?php echo $this->escapeHtml($this->translate('mod-list upload-file label dragover')); ?>
        </label>
        <label class="uploading">
            <?php echo $this->escapeHtml($this->translate('mod-list upload-file label uploading')); ?>
        </label>
    </form>
</section>