<?php

use FactorioItemBrowser\Api\Client\Entity\GenericEntityWithRecipes;
use FactorioItemBrowser\Portal\View\Helper\GenericEntityHelper;

/* @var GenericEntityHelper $genericEntityHelper */
$genericEntityHelper = $this->genericEntity();
/* @var GenericEntityWithRecipes $item */
$item = $this->itemWithProducts;
?>
<div class="item-details-head">
    <?php echo $genericEntityHelper->renderTransparentIcon($item); ?>
    <div class="label">
        <h1><?php echo $this->escapeHtml($this->replace(
            $this->translate('item-details headline ' . $item->getType()),
            ['name' => $item->getLabel() ?: $item->getName()]
        )); ?></h1>
        <?php echo $this->escapeHtml($item->getDescription()); ?>
    </div>
</div>