<?php
use FactorioItemBrowser\Api\Client\Entity\GenericEntityWithRecipes;
use FactorioItemBrowser\Portal\View\Helper\GenericEntityHelper;

/* @var GenericEntityHelper $genericEntityHelper */
$genericEntityHelper = $this->genericEntity();
/* @var array|GenericEntityWithRecipes[] $recipes */
$recipes = $this->ingredientRecipes;
if (count($recipes) > 0) { ?>
    <section>
        <h2><?php echo $this->escapeHtml($this->replace(
            $this->translatePlural('item-details ingredient-in', '', $this->totalNumberOfIngredientRecipes),
            ['count' => $this->totalNumberOfIngredientRecipes]
        )); ?></h2>

        <ul class="item-ingredients-list">
            <?php foreach ($recipes as $recipe) { ?>
                <li><?php echo $genericEntityHelper->renderBox($recipe); ?></li>
            <?php }
            echo $this->render('portal::item/partial/moreRecipes', [
                'currentPage' => 1,
                'item' => $this->item,
                'recipeType' => 'ingredient',
                'totalNumberOfResults' => $this->totalNumberOfIngredientRecipes
            ]); ?>
        </ul>
    </section>
<?php }
