<?php
use FactorioItemBrowser\Api\Client\Entity\GenericEntityWithRecipes;
use FactorioItemBrowser\Portal\View\Helper\GenericEntityHelper;

/* @var GenericEntityHelper $genericEntityHelper */
$genericEntityHelper = $this->genericEntity();
/* @var GenericEntityWithRecipes $item */
$item = $this->itemWithProducts;

if (count($item->getRecipes()) > 0) { ?>
    <section>
        <h2><?php echo $this->escapeHtml($this->replace(
            $this->translatePlural('item-details product-of', '', $item->getTotalNumberOfRecipes()),
            ['count' => $item->getTotalNumberOfRecipes()]
        )); ?></h2>

        <ul class="item-products-list">
            <?php foreach ($item->getRecipes() as $recipe) {
                echo $genericEntityHelper->renderRecipeBox($recipe, 'item-recipe', 'li');
            }
            echo $this->render('portal::item/partial/moreRecipes', [
                'currentPage' => 1,
                'item' => $item,
                'recipeType' => 'product',
            ]); ?>
        </ul>
    </section>
<?php }
