<?php
use FactorioItemBrowser\Portal\Constant\RouteNames;

$this->headTitle()->prepend($this->translate('settings page-title'));

echo $this->render('portal::settings/partial/message');
?>

<form class="settings-form" action="<?php echo $this->escapeHtmlAttr($this->url(RouteNames::SETTINGS_SAVE)); ?>" method="post"><?php
    echo $this->render('portal::settings/partial/recipeModes');
    echo $this->render('portal::settings/partial/locales');
    ?>
    <div class="sticky-submit-button hidden">
        <button type="submit"><?php echo $this->escapeHtml($this->translate('settings button save')); ?></button>
    </div>
</form>