<?php
use FactorioItemBrowser\Api\Client\Entity\GenericEntity;
use FactorioItemBrowser\Api\Client\Entity\GenericEntityWithRecipes;
use FactorioItemBrowser\Portal\View\Helper\RecipeHelper;

/* @var RecipeHelper $recipeHelper */
$recipeHelper = $this->recipe();
/* @var GenericEntity $entity */
$entity = $this->entity;
?>
<<?php echo $this->tagName; ?> class="<?php echo $this->escapeHtmlAttr($this->cssClass); ?>"><?php
    echo $this->render('helper::genericEntity/partial/head');
    if ($entity instanceof GenericEntityWithRecipes) {
        foreach ($entity->getRecipes() as $recipe) {
            echo $this->partial('helper::genericEntity/partial/recipe', ['recipe' => $recipeHelper->getPrimaryRecipe($recipe)]);
            if ($recipeHelper->hasSecondaryRecipe($recipe)) {
                echo $this->partial('helper::genericEntity/partial/recipe', ['recipe' => $recipeHelper->getSecondaryRecipe($recipe)]);
            }
        }
        echo $this->render('helper::genericEntity/partial/omittedRecipes');
    }
?></<?php echo $this->tagName; ?>>