<?php
use FactorioItemBrowser\Api\Client\Entity\GenericEntity;
use FactorioItemBrowser\Api\Client\Entity\Item;
use FactorioItemBrowser\Portal\View\Helper\GenericEntityHelper;

/* @var GenericEntityHelper $genericEntityHelper */
$genericEntityHelper = $this->genericEntity();
/* @var GenericEntity $entity */
$entity = $this->entity;
?>
<a
    href="<?php echo $this->escapeHtmlAttr($genericEntityHelper->getDetailsUrl($entity)); ?>"
    class="icon with-background icon-<?php echo $this->escapeHtmlAttr($entity->getType() . '-' . $entity->getName()); ?>"
    data-icon="<?php echo $this->escapeHtmlAttr($genericEntityHelper->getIcon($entity)); ?>"
    data-tooltip="<?php echo $this->escapeHtmlAttr($genericEntityHelper->getTooltip($entity)); ?>"
    data-link
>
    <?php if ($entity instanceof Item && $entity->getAmount() > 0) { ?>
        <span class="amount"><?php
            echo $this->escapeHtml($genericEntityHelper->formatAmount($entity->getAmount()));
        ?></span>
    <?php } ?>
</a>
