<?php
use FactorioItemBrowser\Api\Client\Entity\GenericEntity;
use FactorioItemBrowser\Portal\View\Helper\GenericEntityHelper;

/* @var GenericEntityHelper $genericEntityHelper */
$genericEntityHelper = $this->genericEntity();
/* @var GenericEntity $entity */
$entity = $this->entity;
?>
<div
    class="icon"
    data-icon="<?php echo $this->escapeHtmlAttr($genericEntityHelper->getIcon($entity)); ?>"
    <?php foreach ($this->attributes as $name => $value) {
        echo $this->escapeHtml($name);
        if (!empty($value)) {
            echo '="' . $this->escapeHtmlAttr($name) . '"';
        }
    }
    ?>
></div>
