<?php

use FactorioItemBrowser\Portal\View\Helper\LocaleHelper;

/* @var LocaleHelper $localeHelper */
$localeHelper = $this->locale();

?>

<div class="sidebar-locale">
    <input type="checkbox" id="toggle-locale" class="toggle-checkbox" />
    <label class="sidebar-locale-label toggle-label" for="toggle-locale">
        <span class="locale-icon"></span>
        <span class="label"><?php
            echo $this->escapeHtml($this->replace($this->translate('sidebar locale label'), [
                'locale' => $this->translate('locale native ' . $localeHelper->getCurrentLocale())
            ]));
        ?></span>
    </label>
    <ul class="sidebar-locale-list toggle-target">
        <?php foreach ($localeHelper->getEnabledLocales() as $locale) { ?>
            <li data-locale="<?php echo $this->escapeHtmlAttr($locale); ?>">
                <?php echo $this->escapeHtml($this->translate('locale native ' . $locale)); ?>
            </li>
        <?php } ?>
    </ul>
    <p class="sidebar-locale-disclaimer toggle-target"><?php
        echo $this->escapeHtml($this->translate('sidebar locale disclaimer'));
    ?></p>
</div>