<?php
use FactorioItemBrowser\Portal\Constant\RouteNames;
?>

<a class="sidebar-mod-link no-loading-circle" href="<?php // echo $this->escapeHtmlAttr($this->url(RouteNames::MODS)); ?>" data-link>
    <div class="mod-link-icon"></div>
    <div class="label">
        <?php echo $this->escapeHtml($this->replace($this->translate('sidebar mod-link label'), [
            'number' => 'X', // @todo Insert actual numbers
            'count' => 'Y'
        ])); ?>
    </div>
</a>