<section>
    <h2><?php echo $this->escapeHtml($this->translate('settings recipe-mode headline')); ?></h2>

    <div class="recipe-modes-list">
        <?php foreach (['hybrid', 'normal', 'expensive'] as $recipeMode) { ?>
            <input
                id="recipeMode_<?php echo $this->escapeHtmlAttr($recipeMode); ?>"
                name="recipeMode"
                value="<?php echo $this->escapeHtmlAttr($recipeMode); ?>"
                type="radio"
                class="recipe-mode-radio hidden"
            />
            <div class="recipe-mode">
                <label for="recipeMode_<?php echo $this->escapeHtmlAttr($recipeMode); ?>">
                    <h3><?php echo $this->escapeHtml($this->translate('settings recipe-mode ' . $recipeMode . ' label')); ?></h3>
                    <?php echo $this->escapeHtml($this->translate('settings recipe-mode ' . $recipeMode . ' description')); ?>
                </label>
                <div class="check-icon"></div>
            </div>
        <?php } ?>
    </div>
</section>