<?php

use FactorioItemBrowser\Api\Client\Entity\GenericEntityWithRecipes;
use FactorioItemBrowser\Portal\View\Helper\GenericEntityHelper;

/* @var GenericEntityHelper $genericEntityHelper */
$genericEntityHelper = $this->genericEntity();
/* @var GenericEntityWithRecipes $item */
$item = $this->itemWithProducts;

$this->headTitle()->prepend($item->getLabel() ?: $item->getName());

echo $this->render('portal::item/partial/head');
echo $this->render('portal::item/partial/products');
echo $this->render('portal::item/partial/ingredients');
