<?php
use FactorioItemBrowser\Api\Client\Entity\GenericEntityWithRecipes;
use FactorioItemBrowser\Portal\View\Helper\GenericEntityHelper;

/* @var GenericEntityHelper $genericEntityHelper */
$genericEntityHelper = $this->genericEntity();
/* @var GenericEntityWithRecipes $item */
$item = $this->item;
?>

<?php foreach ($item->getRecipes() as $recipe) { ?>
    <?php echo $genericEntityHelper->renderRecipeBox($recipe, 'item-recipe', 'li'); ?>
<?php }
echo $this->render('portal::item/partial/moreRecipes'); ?>