<?php
use FactorioItemBrowser\Api\Client\Entity\Machine;

/* @var Machine[] $machines */
$machines = $this->machines;
?>

<section>
    <h2><?php echo $this->escapeHtml($this->replace(
        $this->translatePlural('recipe-details machine headline', '', $this->totalNumberOfMachines),
        ['count' => $this->totalNumberOfMachines]
    )); ?></h2>
    <ul class="machine-list">
        <?php foreach ($machines as $machine) {
            if ($machine->getName() === 'player') {
                echo $this->partial('portal::recipe/partial/machine/player', ['machine' => $machine]);
            } else {
                echo $this->partial('portal::recipe/partial/machine/machine', ['machine' => $machine]);
            }
        } ?>
    </ul>
</section>