<?php

use FactorioItemBrowser\Api\Client\Entity\Recipe;

/* @var Recipe $recipe */
$recipe = $this->recipe;

?>


<section class="recipe-details-container <?php echo $this->escapeHtmlAttr($recipe->getMode()); ?>">
    <?php echo $this->partial('portal::recipe/partial/head', ['recipe' => $recipe]); ?>

    <div class="recipe-details">
        <?php echo $this->partial('portal::recipe/partial/ingredients', ['recipe' => $recipe]); ?>
        <div class="separator"></div>
        <?php echo $this->partial('portal::recipe/partial/products', ['recipe' => $recipe]); ?>
    </div>
</section>