<?php

use FactorioItemBrowser\Api\Client\Entity\GenericEntity;
use FactorioItemBrowser\Api\Client\Entity\Machine;

/* @var Machine $machine */
$machine = $this->machine;
/* @var genericEntity $linkedEntity */
$linkedEntity = $this->genericEntity()->getLinkedEntityOfMachine($machine);
?>
<li class="machine">
    <a class="head"
       href="<?php echo $this->escapeHtmlAttr($this->genericEntity()->getDetailsUrl($linkedEntity)); ?>"
       data-link
       data-tooltip="<?php echo $this->escapeHtmlAttr($this->genericEntity()->getTooltip($linkedEntity)); ?>"
    >
        <?php echo $this->genericEntity()->renderTransparentIcon($machine, ['data-tooltip-anchor' => '']); ?>
        <div class="label">
            <h3><?php echo $this->escapeHtml($machine->getLabel() ?: $machine->getName()); ?></h3>
            <?php echo $this->escapeHtml($machine->getDescription()); ?>
        </div>
    </a>
    <div class="stats">
        <div class="value"><?php echo $this->format()->craftingSpeed($machine->getCraftingSpeed()); ?></div>
        <div class="label"><?php echo $this->escapeHtml($this->translate('recipe-details machine crafting-speed')); ?></div>

        <div class="value"><?php echo $this->format()->machineSlots($machine->getNumberOfItemSlots()); ?></div>
        <div class="label"><?php
            echo $this->escapeHtml($this->translatePlural('recipe-details machine ingredients', '', max($machine->getNumberOfItemSlots(), 0)));
        ?></div>

        <div class="value"><?php echo $this->format()->machineSlots($machine->getNumberOfFluidInputSlots()); ?></div>
        <div class="label"><?php
            echo $this->escapeHtml($this->translatePlural('recipe-details machine fluids', '', max($machine->getNumberOfFluidInputSlots(), 0)));
        ?></div>

        <div class="value"><?php echo $this->format()->machineSlots($machine->getNumberOfModuleSlots()); ?></div>
        <div class="label"><?php
            echo $this->escapeHtml($this->translatePlural('recipe-details machine modules', '', max($machine->getNumberOfModuleSlots(), 0)));
        ?></div>

        <div class="value"><?php echo $this->format()->energyUsage($machine->getEnergyUsage()); ?></div>
        <div class="label"><?php echo $this->escapeHtml($this->translate('recipe-details machine energy-usage')); ?></div>
    </div>
</li>