<?php
use FactorioItemBrowser\Api\Client\Entity\Machine;

/* @var Machine $machine */
$machine = $this->machine;
?>
<li class="machine">
    <div class="head">
        <?php echo $this->genericEntity()->renderTransparentIcon($machine); ?>
        <div class="label">
            <h3><?php echo $this->escapeHtml($machine->getLabel() ?: $machine->getName()); ?></h3>
            <?php echo $this->escapeHtml($machine->getDescription()); ?>
        </div>
    </div>

    <div class="stats">
        <div class="value"><?php echo $this->format()->craftingSpeed($machine->getCraftingSpeed()); ?></div>
        <div class="label"><?php echo $this->escapeHtml($this->translate('recipe-details machine crafting-speed')); ?></div>

        <div class="value"><?php echo $this->format()->machineSlots($machine->getNumberOfItemSlots()); ?></div>
        <div class="label"><?php
            echo $this->escapeHtml($this->translatePlural('recipe-details machine ingredients', '', max($machine->getNumberOfItemSlots(), 0)));
        ?></div>

        <div class="value"><?php echo $this->format()->machineSlots($machine->getNumberOfFluidInputSlots()); ?></div>
        <div class="label"><?php
            echo $this->escapeHtml($this->translatePlural('recipe-details machine fluids', '', max($machine->getNumberOfFluidInputSlots(), 0)));
        ?></div>
    </div>

    <p class="player-notice">
        <?php echo $this->escapeHtmlAttr($this->translate('recipe-details machine player-notice')); ?>
    </p>
</li>